// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $election_requests_id_ from "./routes/election-requests/[id].tsx";
import * as $election_requests_index from "./routes/election-requests/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $organization_requests_id_ from "./routes/organization-requests/[id].tsx";
import * as $organization_requests_index from "./routes/organization-requests/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/election-requests/[id].tsx": $election_requests_id_,
    "./routes/election-requests/index.tsx": $election_requests_index,
    "./routes/index.tsx": $index,
    "./routes/organization-requests/[id].tsx": $organization_requests_id_,
    "./routes/organization-requests/index.tsx": $organization_requests_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
